color0 #121314
color1 #ffb4ab
color2 #b1cada
color3 #bfc8cf
color4 #d3c0dc
color5 #b1cada
color6 #bfc8cf
color7 #e3e2e3
color8 #8c9195
color9 #ffb4ab
color10 #b1cada
color11 #bfc8cf
color12 #d3c0dc
color13 #b1cada
color14 #bfc8cf
color15 #e3e2e3

cursor                #e3e2e3
cursor_text_color     #121314
background            #121314
foreground            #e3e2e3
selection_foreground  #c2c7cb
selection_background  #42474b
active_border_color   #b1cada
inactive_border_color #42474b
url_color             #b1cada

active_tab_foreground   #1b3340
active_tab_background   #b1cada
inactive_tab_foreground #c2c7cb
inactive_tab_background #42474b
cursor_trail_color      #c2c7cb
