# Window Rules Configuration
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# Global Rules
windowrule = suppress_event maximize, match:class .*

# dog-menu
windowrule {
    name = dog-menu
    match:class = ^dog-menu$
    float = on
    center = on
    size = 800 600
}

# Bitwarden
windowrule {
    name = Bitwarden
    match:class = ^chrome-nngceckbapebfimnlniiiahkandclblb-Default$
    float = on
    center = on
    size = (monitor_w*0.2) (monitor_h*0.4)
}

# Nautilus
windowrule {
    name = Nautilus
    match:class = ^org.gnome.Nautilus$
    float = on
    center = on
    size = 800 600
}

# Kitty
windowrule {
    name = Kitty
    match:class = ^kitty$
    float = on
    center = on
    size = 800 600
}

# Todoist
windowrule {
    name = Todoist
    match:class = ^Todoist$
    float = on
    center = on
    size = 800 600
}

# Open Files (File Chooser)
windowrule {
    name = Open Files
    match:title = ^Open Files?$
    float = on
    center = on
    size = 800 600
}

# Window rules for the Boot to Windows script
windowrule {
    name = Boot to Windows Popup
    match:class = ^boot-windows$
    float = on
    center = on
    size = 650 300
    animation = popin
}
